config/routes.rb
Academica4you::Application.routes.draw do

   root 'companies#index'
   
   resources :schools do
    collection do
      get :autocomplete
      get :get_addr_by_pos
     end
   end
   
   resources :companies, only: [:index, :new, :create, :edit, :update, :destroy]
   
   resources :courses, only: [:index, :new, :show, :create, :edit, :update, :destroy]
   
   resources :others, only: [:index]
   
   resources :languages, only: [:index, :new, :create, :edit, :update, :destroy]
   
   get 'courses/update_level_select/:id', :controller=>'courses', :action => 'update_level_select'
   
   resources :residences, only: [:index, :new, :create, :edit, :update, :destroy]
   
   resources :carts, only: [:index]
   
   resources :orders, only: [:new]

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :schools
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :course_durations
	has_many :lnk_school_courses
  	accepts_nested_attributes_for :course_durations, :reject_if => :all_blank, :allow_destroy => true
  	accepts_nested_attributes_for :lnk_school_courses, :reject_if => :all_blank, :allow_destroy => true
end

app/models/course_duration.rb
class CourseDuration < ActiveRecord::Base
	belongs_to :course
end

app/models/course_features.rb
class CourseFeatures < ActiveRecord::Base
end

app/models/currency.rb
class Currency < ActiveRecord::Base
end

app/models/exchange_rate.rb
class ExchangeRate < ActiveRecord::Base
end

app/models/geoplace.rb
class Geoplace < ApplicationRecord
	has_many :lnk_school_geoplaces
	belongs_to :geoplace_type
end

app/models/geoplace_type.rb
class GeoplaceType < ApplicationRecord
	has_many :geoplaces
end

app/models/lang_level.rb
class LangLevel < ActiveRecord::Base
	belongs_to :language
end

app/models/language.rb
class Language < ActiveRecord::Base
	has_many :lang_levels
  	accepts_nested_attributes_for :lang_levels, :reject_if => :all_blank, :allow_destroy => true
end

app/models/residence.rb
class Residence < ActiveRecord::Base
self.inheritance_column = nil
has_many :residence_durations
has_many :residence_features
  	accepts_nested_attributes_for :residence_durations, :reject_if => :all_blank, :allow_destroy => true
  	accepts_nested_attributes_for :residence_features, :reject_if => :all_blank, :allow_destroy => true
end

app/models/school.rb
class School < ActiveRecord::Base
   has_many :lnk_school_courses
   has_many :lnk_school_geoplaces
   accepts_nested_attributes_for :lnk_school_courses, :reject_if => :all_blank, :allow_destroy => true

   belongs_to :company
   
   searchkick text_middle: [:full_address_eng, :name], locations: [:location]
   #searchkick locations: [:location]

   #geocoded_by address: :full_address_eng

   # the callback to set longitude and latitude
   #after_validation :geocode

   def search_data
    attributes.merge(location: {lat: latitude, lon: longitude})
  end
end

app/controllers/others_controller.rb
class OthersController < ApplicationController
	def index
		@languages = Language.all
	end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/others_helper.rb
module OthersHelper
end

app/helpers/school_helper.rb
module SchoolHelper
end

app/views/others/index.html.erb
<div class="menu_holder content_page">
	<div class="container">
		<div class="row">
			<div class="grid_12">
				<nav>
					<ul class="sf-menu header_menu sf-js-enabled">
						<li id="first-li"><%= link_to companies_path do %>Компании<strong></strong><% end %></a></li>
						<li><%= link_to schools_path do %>Школы<strong></strong><% end %></li>
						<li><%= link_to courses_path do %> Курсы<strong></strong><% end %></li>
						<li><%= link_to residences_path do %> Проживание<strong></strong><% end %></li>
						<li id="last-li" class="current"><%= link_to others_path do %> Прочее<strong></strong><% end %></li>
					</ul>
				</nav>
			</div>
		</div>
	</div>
</div>
<div class="container">
 	<div class="row">
		<div class="grid_2">
			<%= link_to "Добавить", new_language_path, :class=>"more_btn", :remote=>true %>
		</div> 	
 	</div>
	<div id="new_language_form" class="grid_8 hline3 marg-left-0"></div>
 	<div class="wrapper hline2">
			<div class="title-box1 v2">
				<h3>Языки</h3>
			</div>
			<div class="title-box2">
				<span class="mar3">ID</span>
				<span class="mar3">Название ENG</span>
				<span>Название RUS</span>
			</div>		
			<ul class="listWithMarker">			
				<% @languages.each do |lang| %>
					<li>
						<div class="grid_1">
							<span class="rank_num"><%= lang.id %></span>					
						</div>
						<div class="grid_2"><%= lang.eng_name %></div>
						<div class="grid_6"><%= lang.rus_name %></div>
						<div class="grid_2">
							<%= link_to edit_language_path(lang), :remote=>true do %> 
								<i class="fa fa-edit"></i>
						 	<% end %>
						 	<%= link_to language_path(lang), :method => 'delete', data: { confirm: 'Удалить язык "'+lang.rus_name+'"?' } do %> 
								<i class="fa fa-trash-o"></i>
						 	<% end %>		
						</div>
					</li>	
				<% end %>
			</ul>
 	</div>
</div>