config/routes.rb
Academica4you::Application.routes.draw do

   root 'companies#index'
   
   resources :schools do
    collection do
      get :autocomplete
      get :get_addr_by_pos
     end
   end
   
   resources :companies, only: [:index, :new, :create, :edit, :update, :destroy]
   
   resources :courses, only: [:index, :new, :show, :create, :edit, :update, :destroy]
   
   resources :others, only: [:index]
   
   resources :languages, only: [:index, :new, :create, :edit, :update, :destroy]
   
   get 'courses/update_level_select/:id', :controller=>'courses', :action => 'update_level_select'
   
   resources :residences, only: [:index, :new, :create, :edit, :update, :destroy]
   
   resources :carts, only: [:index]
   
   resources :orders, only: [:new]

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :schools
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :course_durations
	has_many :lnk_school_courses
  	accepts_nested_attributes_for :course_durations, :reject_if => :all_blank, :allow_destroy => true
  	accepts_nested_attributes_for :lnk_school_courses, :reject_if => :all_blank, :allow_destroy => true
end

app/models/course_duration.rb
class CourseDuration < ActiveRecord::Base
	belongs_to :course
end

app/models/course_features.rb
class CourseFeatures < ActiveRecord::Base
end

app/models/currency.rb
class Currency < ActiveRecord::Base
end

app/models/exchange_rate.rb
class ExchangeRate < ActiveRecord::Base
end

app/models/geoplace.rb
class Geoplace < ApplicationRecord
	has_many :lnk_school_geoplaces
	belongs_to :geoplace_type
end

app/models/geoplace_type.rb
class GeoplaceType < ApplicationRecord
	has_many :geoplaces
end

app/models/lang_level.rb
class LangLevel < ActiveRecord::Base
	belongs_to :language
end

app/models/language.rb
class Language < ActiveRecord::Base
	has_many :lang_levels
  	accepts_nested_attributes_for :lang_levels, :reject_if => :all_blank, :allow_destroy => true
end

app/models/lnk_school_course.rb
class LnkSchoolCourse < ActiveRecord::Base
	belongs_to :course
	belongs_to :school
end

app/models/residence.rb
class Residence < ActiveRecord::Base
self.inheritance_column = nil
has_many :residence_durations
has_many :residence_features
  	accepts_nested_attributes_for :residence_durations, :reject_if => :all_blank, :allow_destroy => true
  	accepts_nested_attributes_for :residence_features, :reject_if => :all_blank, :allow_destroy => true
end

app/models/school.rb
class School < ActiveRecord::Base
   has_many :lnk_school_courses
   has_many :lnk_school_geoplaces
   accepts_nested_attributes_for :lnk_school_courses, :reject_if => :all_blank, :allow_destroy => true

   belongs_to :company
   
   searchkick text_middle: [:full_address_eng, :name], locations: [:location]
   #searchkick locations: [:location]

   #geocoded_by address: :full_address_eng

   # the callback to set longitude and latitude
   #after_validation :geocode

   def search_data
    attributes.merge(location: {lat: latitude, lon: longitude})
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
	def index
		if params[:location].present?
		   bounds = Geocoder.search(params[:location]).first.bounds
		   #puts bounds
		   if bounds.present?
	 	      @schools = School.search "*", where: {location: {top_left: {lat: bounds[2], lon: bounds[1]}, bottom_right: {lat: bounds[0], lon: bounds[3]}}}
		   else
		      @schools = []
		   end
		   #puts @schools.to_json
		else
		   @schools = School.all
		end
		@hash = Gmaps4rails.build_markers(@schools) do |school, marker|
			  marker.lat school.latitude
			  marker.lng school.longitude
		end
	end
	
	def new
		@school = School.new
		@companies = Company.all
		@courses = Course.all
		@schools = School.all

		#ip = nil
		#if Rails.env.production?
		#  ip = request.remote_ip
		#else
		#  ip = Net::HTTP.get(URI.parse('http://checkip.amazonaws.com/')).squish
		#end

		#result = Geocoder.search(ip).first

		#puts result.to_json

		#@southWest = [result.bounds[0], result.bounds[1]]
	    #@northEast = [result.bounds[2], result.bounds[3]]
	end 
	
	def create
		@school = School.new(school_params)		
		if(@school.save)
			logger.info "saving school success"
		else
			logger.info "error when saving school"
		end
		redirect_to schools_path
	end
	
	def edit
    	@school = School.find(params[:id])
    	@companies = Company.all
    	@courses = Course.all
  	end
  	
  	def update
	    @school = School.find(params[:id])
	      if @school.update_attributes(school_params)
		logger.info "updating school success"
	      else
		logger.info "error when updating school"
	      end
	      redirect_to schools_path
  	end
  	
  	def destroy
		@school = School.find(params[:id])
		@school.destroy
		redirect_to schools_path
   end
   
   #def search	
   #end

   def autocomplete
      if params[:term].present?
      	lang =  DetectLanguage.simple_detect(params[:term])
        @res_places = Geocoder.search(params[:term], params: {language: lang}).first(5)
		
		@sugest_results = @res_places.map(&:formatted_address)

		puts @sugest_results.empty?

        if !@sugest_results.empty?
	        #puts @res_places.map(&:formatted_address)
	        #puts @res_places.map(&:short_name)
	        sw_lat = nil
	        sw_lon = nil
	        ne_lat = nil
	        ne_lon = nil

	        @res_places.each do |place|
	        	if sw_lat.nil?
		       		sw_lat = place.bounds[0]
			        sw_lon = place.bounds[1]
			        ne_lat = place.bounds[2]
			        ne_lon = place.bounds[3]
			    else
			    	sw_lat = [sw_lat, place.bounds[0]].max
			        sw_lon = [sw_lon, place.bounds[1]].min
			        ne_lat = [ne_lat, place.bounds[2]].min
			        ne_lon = [ne_lon, place.bounds[3]].max
			    end
	        end

	        @southWest = [sw_lat, sw_lon]
	        @northEast = [ne_lat, ne_lon]

        	@hash = Gmaps4rails.build_markers(@res_places) do |place, marker|
				marker.lat place.latitude
				marker.lng place.longitude
				marker.infowindow place.address
			end
        	render :action => 'autocomplete'
        end
      end
   end

   def get_addr_by_pos
   		if params[:map_pos].present?
   			puts params[:map_pos]
   			@addr_res = Geocoder.search(params[:map_pos]).first
   			puts @addr_res.formatted_address
   			render :action => 'get_addr_by_pos'
   		end
   end
	
   private 
   def school_params 
		params.require(:school).permit(
			:name, 
			:description, 
			:company_id, 
			:world_part, 
			:country, 
			:city, 
			:street, 
			:house, 
			:latitude, 
			:longitude,
			lnk_school_courses_attributes: [:id, :school_id, :course_id, :_destroy]
		)  
   end 
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/others_helper.rb
module OthersHelper
end

app/helpers/school_helper.rb
module SchoolHelper
end

app/views/schools/_addr_sugest.html.erb
<% if !@sugest_results.empty? %>
	<ul class="dropdown-menu" id="dropdown-addr-sugest" aria-labelledby="typeahead">
		<% @sugest_results.each do |result| %>
		     <% puts result %>
		     <li><a href="#">
		     	<span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span>
		     	<%= result %>
		     	</a>
		     </li>
		<% end %>
	</ul>
<% end %>

app/views/schools/_form.html.erb
   	<%= form_for(@school) do |f| %>
		<div class="form-group">
			<%= f.label :full_address_eng %>
			<div class="dropdown" id="addr-sugest">
				  <input id="typeahead" class="form-control dropdown-toggle" type="text" placeholder="Type address" data-toggle="dropdown" autocomplete="off">
			</div>
			<span class="empty-message">*This field is required.</span>
			<span class="error-message">*This is not a valid name.</span>
		</div>
  		<div class="form-group">
  			<%= f.label :name %>
			<%= f.text_field :name, :type=>"text", :class=>"form-control", :placeholder=>"Название*", :data=>{:constraints=>"@Required @JustLetters"} %>
				<span class="empty-message">*This field is required.</span>
				<span class="error-message">*This is not a valid name.</span>
		</div>
  		<div class="form-group">
  			<%= f.label :company_id %>
  			<%= f.select :company_id, options_from_collection_for_select(@companies, "id", "name", @school.company_id), {}, {:class=>"form-control bootstrap-select"} %>	
  		</div>
		<div class="form-group">	
			<%= f.label :description %>
			<%= f.text_area :description, :placeholder=>"Описание*", :class=>"form-control", :data=>{:constraints=>"@Required @Length(min=20,max=999999)"} %>
				<span class="empty-message">*This field is required.</span>
				<span class="error-message">*The message is too short.</span>
		</div>
		<div class="form-group">	
			<%= f.label :latitude %>
			<%= f.text_field :latitude, :type=>"text", :class=>"form-control", :placeholder=>"Широта", :readonly => "readonly" %>
		</div>
		<div class="form-group">
			<%= f.label :longitude %>
			<%= f.text_field :longitude, :type=>"text", :class=>"form-control", :placeholder=>"Долгота",:readonly => "readonly" %>
		</div>			
		<div class="form_btns">
	    	<!--%= link_to 'Сохранить', '#', :data=>{:type=>'submit'}, :class=>"more_btn" %-->
	     	<%= f.submit :'Сохранить', :class=>"btn btn-info" %>
		</div>
	<% end %>

app/views/schools/_lnk_school_course_fields.html.erb
<div class="nested-fields row marBot2">
	<div class="grid_3">
	<%= f.label :course_id_id do %>
  		<%= f.select :course_id, options_from_collection_for_select(@courses, "id", "name", f.object.course_id) %>
	<% end %>
	</div>
	<div class="grid_3">
		<div class="form_btns marTop0">
		  <%= link_to_remove_association "Удалить курс", f %>
		</div>
	</div>
</div>

app/views/schools/_video.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <script>

        // This is the URL of the video you want to load
        var videoUrl = 'http://www.vimeo.com/83927488';

        // This is the oEmbed endpoint for Vimeo (we're using JSON)
        // (Vimeo also supports oEmbed discovery. See the PHP example.)
        var endpoint = 'http://www.vimeo.com/api/oembed.json';

        // Tell Vimeo what function to call
        var callback = 'embedVideo';

        // Put together the URL
        var url = endpoint + '?url=' + encodeURIComponent(videoUrl) + '&callback=' + callback + '&width=320';

        // This function puts the video on the page
        function embedVideo(video) {
            document.getElementById('embed').innerHTML = unescape(video.html);
        }

        // This function loads the data from Vimeo
        function init() {
            var js = document.createElement('script');
            js.setAttribute('type', 'text/javascript');
            js.setAttribute('src', url);
            document.getElementsByTagName('head').item(0).appendChild(js);
        }

        // Call our init function when the page loads
        window.onload = init;

    </script>
</head>
<body>
    <div id="embed">Loading video...</div>

</body>
</html>

app/views/schools/autocomplete.js.erb
$('#dropdown-addr-sugest').remove();

southWest = new google.maps.LatLng(<%=raw @southWest[0] %>,<%=raw @southWest[1] %>);
northEast = new google.maps.LatLng(<%=raw @northEast[0] %>,<%=raw @northEast[1] %>);

mapBounds = new google.maps.LatLngBounds( southWest, northEast );

handler.removeMarkers(markers);

markers = handler.addMarkers(<%=raw @hash.to_json %>,
			  {
		    	draggable: true,
		    	animation: google.maps.Animation.DROP,
		    	cursor: 'grab',
		    	draggingCursor: 'grabbing'
		      });

map = handler.getMap();
map.fitBounds(mapBounds);

$('#addr-sugest').append("<%= j render :partial => 'addr_sugest' %>");

app/views/schools/create.js.erb
$( "#new_school_form" ).empty();
alert("Новая школа добавлена");

app/views/schools/edit.js.erb
$('#new_school_form').html("<%= j(render :partial=> 'form') %>");

app/views/schools/get_addr_by_pos.js.erb
$("#typeahead").val("<%= j @addr_res.formatted_address %>");

app/views/schools/index.html.erb
 
<div class="container  pad-top-bot-50">
 <div class="row"> 
 	<div class="col-lg-8">
		<div class="panel panel-default">
	       <div class="panel-heading"><h3 class="panel-title">Поиск на карте</h3></div>
	       <div class="panel-body pad-0" id="map_canvas" style="height:412px;">
	       </div>
	     </div>
 	</div>
	<div class="col-lg-4">
		<div class="panel panel-default">
	       <div class="panel-heading">Выбор программы</div>
	       <div class="panel-body">
		        <%= form_tag schools_path, method: :get do %>
		        		<div class="col-lg-8">
						  <%= text_field_tag :location, params[:location], :data=>{:style=>"btn-info"} %>
						  <%= hidden_field_tag :distance, params[:distance], :value => 100 %>						
						</div>
						<div class="col-lg-4">						
						  <%= submit_tag "Поиск", :class=>"btn btn-success" %>
						</div>
				  <% end %>
	       </div>
	       <!--div class="panel-body">
	       	<div class="col-lg-8">
	       		<%= select_tag :language_id, 
	       		options_for_select([ "Курсы английского", "Подготовка к экзаменам","Учебный семестр/год", "Учеба/работа" ], "Курсы английского"), 
	       		:class=>"selectpicker", :data=>{:style=>"btn-info"} %>
	       	</div>
	       	<div class="col-lg-4">
	       		<%= link_to "", :class=>"btn btn-success" do %>
	       			Поиск
	       		<% end %>
	       	</div>
	       </div-->
	     </div>
		<div class="panel panel-default">
	       <div class="panel-heading">Выбор стран</div>
	       <div class="panel-body">
	       	<div class="col-lg-6">
		         <div class="checkbox">
		         	<label><input type="checkbox"> Австралия</label>
		         </div>
		         <div class="checkbox">
		            <label><input type="checkbox"> Америка</label>
		         </div>
		         <div class="checkbox">
		            <label><input type="checkbox"> Великобритания</label>
		         </div>
		         <div class="checkbox">
		            <label><input type="checkbox"> Германия</label>
		        	</div>
		      </div>
		      <div class="col-lg-6">
		        	<div class="checkbox">
		            <label><input type="checkbox"> Мальта</label>
		         </div>
		         <div class="checkbox">
		            <label><input type="checkbox"> Новая зеландия</label>
		         </div>
		         <div class="checkbox">
		            <label><input type="checkbox"> Франция</label>
		         </div>
					<div class="checkbox">
		            <label><input type="checkbox"> ЮАР</label>
		         </div>
		      </div>
	       </div>
	     </div>
	     
	     <div class="panel panel-default">
	       <div class="panel-heading">Предполагаемое время поездки</div>
	       <div class="panel-body">
	       <div class="col-lg-6">
	       	<div class="input-group" id='datetimepicker1'>	      
			      <input type="text" class="form-control date pad-0">
			      <span class="input-group-btn">
                	<button class="btn btn-info" type="button">
							<span class="glyphicon glyphicon-calendar"></span>                	
                	</button>
              	</span>
			   </div>
			  </div>
			  <div class="col-lg-6">
			   <div class="input-group" id='datetimepicker2'>	      
			      <input type="text" class="form-control date pad-0">
			      <span class="input-group-btn">
                	<button class="btn btn-info" type="button">
							<span class="glyphicon glyphicon-calendar"></span>                	
                	</button>
              	</span>
			   </div>
			  </div>
	       </div>
	     </div>
	     
 	</div> 
 </div>
 <div class="row">
 	<div class="col-lg-12">
	 	<div class="panel panel-default">
	       <div class="panel-heading">
	         <h3 class="panel-title">Результаты поиска</h3>
	       </div>
	   </div>
      <% @schools.each do |school| %>
 	   <div class="panel panel-default">
 	  		<div class="panel-body course-item">
    			<div class="col-lg-2 pad-left-0">
    				<div style="width:100%; margin-bottom: 15px;">
    					<div class="comp-logo">
    						<%= image_tag('eflogo.png', :class=>"row-h-30") %>
    						<%= school.company.name %>
						</div>    				
    				</div>
    				<%= image_tag('00.jpg', :style=>"width: 100%;") %>
    			</div>
    			<div class="col-lg-8">
    				<div class="well course-item-well ">
    					<h4>Школа: <%= school.name %></h4>
    					<p>Язык: Английский</p>
    					<p>Продолжительность: от 2 до 12 недель</p>
    					<p>Минимальный уровень языка: Intermediate</p>
    				</div>
    				<div class="well course-item-well mar-bot-0">
    					<p>Страны: Америка, Мальта</p>
    				</div>
    			</div>
				<div class="col-lg-2 pad-right-0">
					<div class="well course-item-well">
						<h4>от $230</h4>
					</div>
					<%= link_to "Подробнее", course_path(1), :class=>"btn btn-success btn-block" %>
					<button type="submit" class="btn btn-info btn-block">Заказать</button>
    			</div>
  			</div>
 	  </div> 
 	  <% end %> 
 	  
 	</div>
 </div>
 </div>

 
<script type="text/javascript">
      $( document ).ready(function() {
           $('#datetimepicker1').datetimepicker({
                    language: 'ru',
                    pickTime: false,
                    useCurrent: true
           });
           $('#datetimepicker2').datetimepicker({
                    language: 'ru',
                    pickTime: false,
                    useCurrent: true
           });
		
           handler =  Gmaps.build('Google');
	   	 handler.buildMap({ provider: {}, internal: {id: 'map_canvas'}}, function(){
	     markers = handler.addMarkers(<%=raw @hash.to_json %>);
	     handler.bounds.extendWith(markers);
	     handler.fitMapToBounds();
	   });
      });
  </script>

  <script type="text/javascript">

	var states = new Bloodhound({
	  datumTokenizer: Bloodhound.tokenizers.whitespace,
	  queryTokenizer: Bloodhound.tokenizers.whitespace,
	  local: []
	});

	$('#bloodhound .typeahead').typeahead({
	  hint: true,
	  highlight: true,
	  minLength: 1
	},
	{
	  name: 'states',
	  source: states
	});

</script>
  
  

app/views/schools/new.html.erb
<div class="container">
	<div class="row">
		<div>
			<h3>Новая школа</h3>
	 	</div> 
		<div class="col-sm-4">
			
			<%= render partial: "form"%>
		</div>
		<div class="col-sm-8">
			<div class="panel-body pad-0" id="map_canvas" style="height:412px;"></div>
		</div>
 	</div>
	<div class="row">
		<div>
			<h3>Школы</h3>
		</div>
		<table class="table table-hover">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Название школы</th>
		      <th scope="col">Компания</th>
		      <th scope="col">Адрес</th>
		      <th scope="col"></th>
		      <th scope="col"></th>
		    </tr>
		  </thead>
		  <tbody>
		  	<% @schools.each do |school| %>
			    <tr>
			      <th scope="row"><%= school.id %></th>
			      <td><%= school.name %></td>
			      <td><%= school.company.name %></td>
			      <td><%= school.full_address_rus %></td>
			      <td><%= link_to edit_school_path(school), :remote=>true do %> 
						  edit
				 	  <% end %>
				  </td>
				  <td><%= link_to school_path(school), 
				  			:method => 'delete', 
				  			 data: { confirm: 'Удалить школу "'+school.name+'"?' } do 
				  	   %> 
						  delete
				 	  <% end %>
				  </td>
			    </tr>
		    <% end %>
		  </tbody>
		</table>
	</div>
</div>

<script type="text/javascript">
    $( document ).ready(function() {

        handler =  Gmaps.build('Google');
	    handler.buildMap({ provider: {}, internal: 
	    	{
	    		id: 'map_canvas', 
	    	}}, function(){});

	    if (navigator.geolocation) {
		    navigator.geolocation.getCurrentPosition(function(position){

		    	var pos = {
	              lat: position.coords.latitude,
	              lng: position.coords.longitude
	            };
	            map = handler.getMap();
	            map.setCenter(pos);
	            map.setZoom(10);
	            map.setOptions({draggableCursor: 'default'});
		    });
		} else {
		    console.log("Geolocation is not supported by this browser.");
		}
		markers = [];
		google.maps.event.addListener(handler.getMap(), 'click', function(event) {
		    if(markers.length > 0) {
		    	handler.removeMarkers(markers);
		    }
		    markers = handler.addMarkers([
		      {
		        "lat": event.latLng.lat(),
		        "lng": event.latLng.lng()
		      }
		    ],
		      {
		    	draggable: true,
		    	animation: google.maps.Animation.DROP,
		    	cursor: 'grab',
		    	draggingCursor: 'grabbing'
		      }
		    );
		    //alert(markers[0].position.lat());
		    google.maps.event.addListener(markers[0], 'dragend', function(event) {
		    	alert(1);
		    	//$("#school_latitude").val(event.position.lat());
		    	//$("#school_longitude").val(event.position.lng());
		    });
		    params = {map_pos: event.latLng.lat()+","+event.latLng.lng()};
		    $("#school_latitude").val(event.latLng.lat());
		    $("#school_longitude").val(event.latLng.lng());
			$.get('/schools/get_addr_by_pos', params);
		});
    });


  </script>

<script type="text/javascript">
	window.addEventListener("keydown", function(e) {
	    // space and arrow keys
	    if([32, 38, 40].indexOf(e.keyCode) > -1) {
	        e.preventDefault();
	    }
	}, false);
</script>

<script type="text/javascript">

	var prevInputVal = "";
	var typingTimer;              
	var doneTypingInterval = 1000;


	$("#typeahead").on("change paste keyup", function(event) {
	   	
	   	clearTimeout(typingTimer);

		var keycode = (event.keyCode ? event.keyCode : event.which);
		
		if(keycode == '40' && $(this).next().find('a').length > 0){
			$(this).next().find('li:first a').focus();
			$('#typeahead').val($.trim($(this).next().find('li:first a').text()));
		}
	   	else if($("#typeahead").val().length >= 2 && prevInputVal != $("#typeahead").val() && [37, 39].indexOf(event.keyCode) == -1) {
	   		typingTimer = setTimeout(function(){
	   			prevInputVal = $("#typeahead").val();
		   		params = {term: $("#typeahead").val()};
				$.get('/schools/autocomplete', params);
		 	},doneTypingInterval);
		}
	});

  	$(document.body).on('click', '#dropdown-addr-sugest li a' ,function(event){
	    event.preventDefault();
	    $('#typeahead').val($.trim($(this).text()));
	});


	$(document.body).on('keyup', '#dropdown-addr-sugest li' ,function(event){
		var keycode = (event.keyCode ? event.keyCode : event.which);
	    if(keycode == '40' && $(this).next().find('a').length > 0){
			$(this).next().find('a').focus();
			$('#typeahead').val($.trim($(this).next().text()));
		}
		if(keycode == '38' && $(this).prev().find('a').length > 0){
			$(this).prev().find('a').focus();
			$('#typeahead').val($.trim($(this).prev().text()));
		}
	});
</script>

app/views/schools/new.js.erb
$('#new_school_form').html("<%= j(render :partial=> 'form') %>");

app/views/schools/update.js.erb
$( "#new_school_form" ).empty();
alert("Данные о школе обновлены");