config/routes.rb
Academica4you::Application.routes.draw do

   root 'companies#index'
   
   resources :schools do
    collection do
      get :autocomplete
      get :get_addr_by_pos
     end
   end
   
   resources :companies, only: [:index, :new, :create, :edit, :update, :destroy]
   
   resources :courses, only: [:index, :new, :show, :create, :edit, :update, :destroy]
   
   resources :others, only: [:index]
   
   resources :languages, only: [:index, :new, :create, :edit, :update, :destroy]
   
   get 'courses/update_level_select/:id', :controller=>'courses', :action => 'update_level_select'
   
   resources :residences, only: [:index, :new, :create, :edit, :update, :destroy]
   
   resources :carts, only: [:index]
   
   resources :orders, only: [:new]

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :schools
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :course_durations
	has_many :lnk_school_courses
  	accepts_nested_attributes_for :course_durations, :reject_if => :all_blank, :allow_destroy => true
  	accepts_nested_attributes_for :lnk_school_courses, :reject_if => :all_blank, :allow_destroy => true
end

app/models/course_duration.rb
class CourseDuration < ActiveRecord::Base
	belongs_to :course
end

app/models/course_features.rb
class CourseFeatures < ActiveRecord::Base
end

app/models/currency.rb
class Currency < ActiveRecord::Base
end

app/models/exchange_rate.rb
class ExchangeRate < ActiveRecord::Base
end

app/models/geoplace.rb
class Geoplace < ApplicationRecord
	has_many :lnk_school_geoplaces
	belongs_to :geoplace_type
end

app/models/geoplace_type.rb
class GeoplaceType < ApplicationRecord
	has_many :geoplaces
end

app/models/lang_level.rb
class LangLevel < ActiveRecord::Base
	belongs_to :language
end

app/models/language.rb
class Language < ActiveRecord::Base
	has_many :lang_levels
  	accepts_nested_attributes_for :lang_levels, :reject_if => :all_blank, :allow_destroy => true
end

app/models/residence.rb
class Residence < ActiveRecord::Base
self.inheritance_column = nil
has_many :residence_durations
has_many :residence_features
  	accepts_nested_attributes_for :residence_durations, :reject_if => :all_blank, :allow_destroy => true
  	accepts_nested_attributes_for :residence_features, :reject_if => :all_blank, :allow_destroy => true
end

app/models/school.rb
class School < ActiveRecord::Base
   has_many :lnk_school_courses
   has_many :lnk_school_geoplaces
   accepts_nested_attributes_for :lnk_school_courses, :reject_if => :all_blank, :allow_destroy => true

   belongs_to :company
   
   searchkick text_middle: [:full_address_eng, :name], locations: [:location]
   #searchkick locations: [:location]

   #geocoded_by address: :full_address_eng

   # the callback to set longitude and latitude
   #after_validation :geocode

   def search_data
    attributes.merge(location: {lat: latitude, lon: longitude})
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@courses = Course.all
	end 
	
	def new
		@course = Course.new
		@languages = Language.all
		@levels = LangLevel.where(:language_id=>@languages.first.id)
		@schools = School.all
	end 
	
	def create
		@course = Course.new(course_params)		
		if(@course.save)
			logger.info "saving course success"
		else
			logger.info "error when saving course"
		end
		redirect_to courses_path
	end
	
	def edit
    	@course = Course.find(params[:id])
    	@languages = Language.all
    	@schools = School.all
    	@levels = LangLevel.where(:language_id=>@course.language_id).order(:name) unless params[:id].blank?
  	end
  	
  	def update
    @course = Course.find(params[:id])
      if @course.update_attributes(course_params)
        logger.info "updating course success"
      else
        logger.info "error when updating course"
      end
      redirect_to courses_path
  	end
  	
  	def destroy
    @course = Course.find(params[:id])
    @course.destroy
    redirect_to courses_path
   end
	
	def update_level_select
    @levels = LangLevel.where(:language_id=>params[:id]).order(:name) unless params[:id].blank?
	end
	
	private
	def lang_level_params
		params.require(:lang_level).permit(:name, :description, :language_id)
	end

	private 
 	def course_params 
  		params.require(:course).permit(:name, :description, :language_id, :level_id, :minimum_age, 
  						course_durations_attributes: [:id, :course_id, :duration, :type, :price, :currency_id, :_destroy],
  						lnk_school_courses_attributes: [:id, :school_id, :course_id, :_destroy]) 
 	end 
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/others_helper.rb
module OthersHelper
end

app/helpers/school_helper.rb
module SchoolHelper
end

app/views/courses/_course_duration_fields.html.erb
<div class="nested-fields row marBot2">
	<div class="grid_3">
	<%= f.label :duration, :class=>"field" do %>
		<%= f.text_field :duration, :type=>"text", :placeholder=>"Продолжительность курса" %>
	<% end %>
	<%= f.label :price, :class=>"field" do %>
		<%= f.text_field :price, :type=>"text", :placeholder=>"Стоимость" %>
	<% end %>
	</div>
	<div class="grid_3">
		<div class="form_btns marTop0">
		  <%= link_to_remove_association "Удалить время", f %>
		</div>
	</div>
</div>

app/views/courses/_form.html.erb
	 <div class="title-box1 v2">
		<h3>Новый курс</h3>
	 </div>  
  	<%= form_for(@course, :html=>{:class=>"contact-form"}) do |f| %>
  		<div class="success-message">Contact form submitted!</div>
			<%= f.label :name do %>
				<%= f.text_field :name, :type=>"text", :placeholder=>"Название курса" %>
			<% end %>
			<%= f.label :language_id do %>
  				<%= f.select :language_id, options_from_collection_for_select(@languages, "id", "rus_name", @course.language_id ) %>
			<% end %>	
			
			<%= f.label :lang_level_id do %>
					 <%= f.select :level_id, options_from_collection_for_select(@levels, "id", "name", @course.level_id ) %>
			<% end %>	
			
			<%= f.label :minimum_age do %>
				<%= f.text_field :minimum_age, :type=>"text", :placeholder=>"Минимальный возраст" %>
			<% end %>
			
			<%= f.label :class=>"message" do %>
				<%= f.text_area :description, :placeholder=>"Описание", :data=>{:constraints=>"@Required @Length(min=20,max=999999)"} %>
				<span class="empty-message">*This field is required.</span>
				<span class="error-message">*The message is too short.</span>
			<% end %>
			
			<div class="form_btns title-box1 v2">
				<h3>Продолжительность курса</h3>
	 		</div>  
			<%= f.label :course_durations do %>
				<%= f.fields_for :course_durations do |d| %>
	      		<%= render 'course_duration_fields', :f => d %>
	      	<% end %>
	      <% end %>
	      
      	<div class="form_btns">
   			<%= link_to_add_association f, :course_durations do %>
   				 Добавить продолжительность
   				 <i class="fa fa-plus"></i>
   			<% end %>
      	</div>
      	
      	<div class="form_btns title-box1 v2">
				<h3>Школы</h3>
	 		</div>  
			<%= f.label :lnk_school_courses do %>
				<%= f.fields_for :lnk_school_courses do |d| %>
	      		<%= render 'lnk_school_course_fields', :f => d %>
	      	<% end %>
	      <% end %>
	      
      	<div class="form_btns">
   			<%= link_to_add_association f, :lnk_school_courses do %>
   				 Добавить школу
   				 <i class="fa fa-plus"></i>
   			<% end %>
      	</div>
	      				
		   <div class="form_btns">
	     		<!--%= link_to 'Сохранить', '#', :data=>{:type=>'submit'}, :class=>"more_btn" %-->
	     		<%= f.submit :'Сохранить', :class=>"more_btn" %>
			</div>
	<% end %>
	
	<script>
	jQuery(function($) {
	  // when the #language field changes
	  $("#course_language_id").change(function() {
	    // make a POST call and replace the content
	    var language = $('select#course_language_id :selected').val();
	    if(language == "") language="0";
	    jQuery.get('/courses/update_level_select/' + language, function(data){
	        $("#course_lang_level_id").html(data);
	    })
	    return false;
	  });
	
	})
	</script>

app/views/courses/_lnk_school_course_fields.html.erb
<div class="nested-fields row marBot2">
	<div class="grid_3">
	<%= f.label :school_id do %>
  		<%= f.select :school_id, options_from_collection_for_select(@schools, "id", "name", f.object.school_id) %>
	<% end %>
	</div>
	<div class="grid_3">
		<div class="form_btns marTop0">
		  <%= link_to_remove_association "Удалить школу", f %>
		</div>
	</div>
</div>

app/views/courses/edit.js.erb
$('#new_course_form').html("<%= j(render :partial=> 'form') %>");

app/views/courses/index.html.erb
<div class="menu_holder content_page">
	<div class="container">
		<div class="row">
			<div class="grid_12">
				<nav>
					<ul class="sf-menu header_menu sf-js-enabled">
						<li id="first-li"><%= link_to companies_path do %>Компании<strong></strong><% end %></a></li>
						<li><%= link_to schools_path do %>Школы<strong></strong><% end %></li>
						<li class="current"><%= link_to courses_path do %> Курсы<strong></strong><% end %></li>
						<li><%= link_to residences_path do %> Проживание<strong></strong><% end %></li>
						<li id="last-li"><%= link_to others_path do %> Прочее<strong></strong><% end %></li>
					</ul>
				</nav>
			</div>
		</div>
	</div>
</div>
<div class="container">
 	<div class="row">
		<div class="grid_2">
			<%= link_to "Добавить", new_course_path, :class=>"more_btn", :remote=>true %>
		</div> 	
 	</div>
	<div id="new_course_form" class="grid_8 hline3 marg-left-0"></div>
 	<div class="wrapper hline2">
			<div class="title-box1 v2">
				<h3>Курсы</h3>
			</div>
			<div class="title-box2">
				<span class="mar3">ID</span>
				<span class="mar3">Название</span>
				<span>Описание</span>
			</div>		
			<ul class="listWithMarker">			
				<% @courses.each do |course| %>
					<li>
						<div class="grid_1">
							<span class="rank_num"><%= course.id %></span>					
						</div>
						<div class="grid_2"><%= course.name %></div>
						<div class="grid_6"><%= course.description %></div>
						<div class="grid_2">
							<%= link_to edit_course_path(course), :remote=>true do %> 
								<i class="fa fa-edit"></i>
						 	<% end %>
						 	<%= link_to course_path(course), :method => 'delete', data: { confirm: 'Удалить курс "'+course.name+'"?' } do %> 
								<i class="fa fa-trash-o"></i>
						 	<% end %>		
						</div>
					</li>	
				<% end %>
			</ul>
 	</div>
</div>

app/views/courses/new.js.erb
$('#new_course_form').html("<%= j(render :partial=> 'form') %>");

app/views/courses/show.html.erb
<div class="container  pad-top-bot-50">
 <div class="row"> 
 	<div class="col-lg-9">
		<div class="panel panel-default">
	       <div class="panel-heading"><h3 class="panel-title">Программа обучения</h3></div>
	       <div class="panel-body panel-grey">
	       	 <div class="row col-lg-6 mar-left-0">
	       	 		<div class="well pad-0 panel-grey">
    	 					<h3 class="mar-0">Курс: <span style="text-decoration:underline" >Английский на отдыхе</span></h3>
       	 			</div>
       	 			<p><b>Тип:</b> <span style="text-decoration:underline" >общий курс</span></p>
       	 			<p><b>Школа:</b> <%= link_to "London Covent Garden", "" %></p>
       	 			<p><b>Место:</b> <span style="text-decoration:underline" >Лондон, Великобритания</span></p>
       	 			<p><b>Начало занятий:</b> <span style="text-decoration:underline" >каждую 2-ю неделю месяца</span></p>
       	 			<p>
	 	 						Эта программа языковой школы Каплан разработана таким образом, чтобы помочь вам улучшить ваши 
								знания английского языка, при этом оставляя много свободного времени для осмотра достопримечательностей и 
								развлекательных мероприятий
						</p>
						<p>
							<b><span class="glyphicon glyphicon-map-marker"> 
								</span> Курс доступен в школах:
							</b>
							<%= link_to "EF Malta (Мальта)", "" %>,
							<%= link_to "EF Dublin (Ирландия)", "" %>,
							<%= link_to "EF Florida (США)", "" %>
						</p>
	       	 </div>
	       	 <div class="row col-lg-6 mar-left-20">
				   	<p><%= image_tag "EC_2.jpg", :class=>"img-responsive" %></p>
				   	<div class="row pad-10">
							<div class="col-lg-3 pad-5">
								<div class="alert alert-info mar-bot-0 pad-5 pad-top-12 m-height-80">
									<%= image_tag "eflogo.png", :class=>"absolute-center img-responsive" %>
								</div>
							</div> 
							<div class="col-lg-9 pad-5">
								<div class="well pad-10 panel-dark-grey m-height-80 mar-bot-0">
									<h4 class="mar-top-0">	
										<span style="text-decoration:underline">
											Education First
										</span>
									</h4>
									<%= link_to "" do %>
										Смотреть все курсы школы
										<span class="glyphicon glyphicon-share-alt"></span> 
									<% end %>
       	 					</div>
       	 				</div>    	 			
       	 			</div> 
				 </div>
	       </div>
	    </div>
	    <div class="row">
	    	<div class="col-lg-6">
	    		<div class="panel panel-default">
		       	<div class="panel-heading">
						<span class="glyphicon glyphicon-plus-sign"> </span> В стоимость курса включено</div>
		       	<div class="scrolled">
		       		<table class="table table-striped">
					      <tbody>
					        <tr>
					        	 <td><span class="glyphicon glyphicon-ok text-green"> </span></td>
					          <td>Приветственный пакет</td>
					        </tr>
					        <tr>
					        	 <td><span class="glyphicon glyphicon-ok text-green"> </span></td>
					          <td>Ориентационная прогулка по городу + приветственный вечер</td>
					        </tr>
					        <tr>
					          <td><span class="glyphicon glyphicon-ok text-green"> </span></td>
					          <td>Зумба – урок танцев в Латино баре ФУЭГО</td>
					        </tr>
					        <tr>
					        	 <td><span class="glyphicon glyphicon-ok text-green"> </span></td>
					          <td>Фильм</td>
					        </tr>
					        <tr>
					        	 <td><span class="glyphicon glyphicon-ok text-green"> </span></td>
					          <td>Спец.предложение в ресторане “ВИЛЛА” в Сан Джулиансе</td>
					        </tr>
					      </tbody>
					    </table>
		         </div>
		      </div>
	    	</div>
	    	<div class="col-lg-6">
	    		<div class="panel panel-default">
		       	<div class="panel-heading">
						<span class="glyphicon glyphicon-star"> </span> Особенности</div>
		       	<div class="panel-body panel-grey">
		       		<div class="row">
							 <div class="col-lg-6">
					          <div class="alert alert-info m-height-110 text-center">
					                <span class="glyphicon glyphicon-bullhorn"></span> 							
										 <span style="text-decoration:underline">Изучаемый язык</span>:</br>
										 <b>Английский</b>
					              </div>
					          </div> 	
					          <div class="col-lg-6">
					              <div class="alert alert-danger m-height-110 text-center">
					                <span class="glyphicon glyphicon-user"></span> 
									    <span style="text-decoration:underline">Минимальный возраст</span>:</br>							
									    <b>16 лет</b>
					              </div>
					          </div> 	
					          <div class="col-lg-6">
					              <div class="alert alert-primary m-height-110 text-center">
					                <span class="glyphicon glyphicon-sort-by-attributes"></span> 
									    <span style="text-decoration:underline">Минимальный уровень языка</span>:</br>								
									    <b>Элементарный</b>
					              </div>
					          </div> 	
								 <div class="col-lg-6">
					              <div class="alert alert-warning m-height-110 text-center">
					                <span class="glyphicon glyphicon-time"></span> 
										 <span style="text-decoration:underline">Длительность занятий</span>:</br> 								
										 <b>45 минут</b>
					              </div>
					          </div> 
					    </div>  
		         </div>
		      </div>
	    	</div>
	    </div>
    	 <div class="panel panel-default">
       	<div class="panel-heading">
       		<span class="glyphicon glyphicon-cog"> </span> Варианты курсов
       	</div>
       	<div class="scrolled">
	         <table class="table table-hover">
	           <thead>
			        <tr>
			          <th>Название</th>
			          <th>Человек в группе</th>
			          <th>Занятий в неделю</th>
			          <th>1 занятие</th>
			          <th>Кол-во недель</th>
			          <th>Стоимость</th>
			          <th></th>
			        </tr>
			     </thead>
		        <tbody>
		          <tr>
		            <td>Стандартные групповые курсы английского</td>
		            <td>до 12</td>
		            <td>20</td>
		            <td>45 мин.</td>
		            <td>
		            	<%= select_tag :language_id, 
	       					options_for_select([ "1 неделя", "2 недели","3 недели", "4 недели" ], "1 неделя"), 
	       					:class=>"selectpicker", :data=>{:style=>"btn-info btn-sm"} %>
		            </td>
		            <td>€100</td>
		            <td><%= link_to "В корзину", "", :class=>"btn btn-info btn-sm" %></td>
		          </tr>
		          <tr>
		            <td>Стандартные групповые курсы английского</td>
		            <td>до 12</td>
		            <td>20</td>
		            <td>45 мин.</td>
		            <td>
		            	<%= select_tag :language_id, 
	       					options_for_select([ "1 неделя", "2 недели","3 недели", "4 недели" ], "1 неделя"), 
	       					:class=>"selectpicker", :data=>{:style=>"btn-info btn-sm"} %>
		            </td>
		            <td>€100</td>
		            <td><%= link_to "В корзину", "", :class=>"btn btn-info btn-sm" %></td>
		          </tr>
		          <tr>
		            <td>Стандартные групповые курсы английского</td>
		            <td>до 12</td>
		            <td>20</td>
		            <td>45 мин.</td>
		            <td>
		            	<%= select_tag :language_id, 
	       					options_for_select([ "1 неделя", "2 недели","3 недели", "4 недели" ], "1 неделя"), 
	       					:class=>"selectpicker", :data=>{:style=>"btn-info btn-sm"} %>
		            </td>
		            <td>€100</td>
		            <td><%= link_to "В корзину", "", :class=>"btn btn-info btn-sm" %></td>
		          </tr>
		        </tbody>
			    </table>
			 </div>
       </div>
       <div class="panel panel-default">
       	<div class="panel-heading">
       		<span class="glyphicon glyphicon-home"> </span> Проживание</div>
       	   <div class="scrolled">
	         <table class="table table-hover">
	           <thead>
			        <tr>
			          <th>Название</th>
			          <th>Описание</th>
			          <th>Кол-во недель</th>
			          <th>Стоимость</th>
			          <th></th>
			        </tr>
			     </thead>
		        <tbody>
		          <tr>
		            <td>Резиденция Magenta House</td>
		            <td>Проживание в резиденции в комнате на одного. Без еды</td>
		            <td>
		            	<%= select_tag :language_id, 
	       					options_for_select([ "1 неделя", "2 недели","3 недели", "4 недели" ], "1 неделя"), 
	       					:class=>"selectpicker", :data=>{:style=>"btn-info btn-sm"} %>
		            </td>
		            <td>€100</td>
		            <td><%= link_to "В корзину", "", :class=>"btn btn-info btn-sm" %></td>
		          </tr>
		          <tr>
		            <td>Проживание в семье</td>
		            <td>Комната на двоих. 3-4 питание 14 раз в неделю</td>
		            <td>
		            	<%= select_tag :language_id, 
	       					options_for_select([ "1 неделя", "2 недели","3 недели", "4 недели" ], "1 неделя"), 
	       					:class=>"selectpicker", :data=>{:style=>"btn-info btn-sm"} %>
		            </td>
		            <td>€100</td>
		            <td><%= link_to "В корзину", "", :class=>"btn btn-info btn-sm" %></td>
		          </tr>
		        </tbody>
			    </table>
       	</div>
       </div>
       <div class="panel panel-default">
       	<div class="panel-heading">
				<span class="glyphicon glyphicon-star"> </span> Похожие курсы</div>
       	<div class="panel-body panel-grey">
       		<div class="row">
			      <div class="col-xs-6 col-md-3">
			        <div class="thumbnail">
			          <div class="thumb-top">ЕС Мальта от €150</div>
				       <%= image_tag "EC_2.jpg", :class=>"img-responsive" %>
				       <%= link_to "Посмотреть", "", :class=>"btn btn-info btn-sm btn-block" %>
				     </div> 
			      </div>
			      <div class="col-xs-6 col-md-3">
			        <div class="thumbnail">
				       <div class="thumb-top">ЕС Мальта от €150</div>
				       <%= image_tag "EC_3.jpg", :class=>"img-responsive" %>
				       <%= link_to "Посмотреть", "", :class=>"btn btn-info btn-sm btn-block" %>
				     </div>  
			      </div>
			      <div class="col-xs-6 col-md-3">
			        <div class="thumbnail">
				        <div class="thumb-top">ЕС Мальта от €150</div>
				       <%= image_tag "EC_4.jpg", :class=>"img-responsive" %>
				       <%= link_to "Посмотреть", "", :class=>"btn btn-info btn-sm btn-block" %>
				     </div>  
			      </div>
			      <div class="col-xs-6 col-md-3">
			        <div class="thumbnail">
				       <div class="thumb-top">ЕС Канада от $120</div>
				       <%= image_tag "EC_1.jpg", :class=>"img-responsive" %>
				       <%= link_to "Посмотреть", "", :class=>"btn btn-info btn-sm btn-block" %>
				     </div> 
			      </div>
			    </div>       
       	</div>
       </div>
 	</div>
	<div class="col-lg-3">
       <div class="thumbnail panel-grey video-thumb">
          <%= link_to "" do %>
          	<%= image_tag "EC_4.jpg", :class=>"img-responsive" %>
				<span class="glyphicon glyphicon-play"></span>
          <% end %>
          <div class="caption">
            <!--p><a href="#" class="btn btn-primary" role="button">Button</a> 
            <a href="#" class="btn btn-default" role="button">Button</a></p-->
          </div>
        </div>
       <%= link_to carts_path, :class=>"btn btn-success btn-lg btn-block" do %>
			<span class="glyphicon glyphicon-shopping-cart"></span>			
       	Корзина
 			<sup><span class="badge">2</span></sup>      	
       <% end %> 
       <%= link_to "", :class=>"btn btn-warning btn-lg btn-block" do %>
			<span class="glyphicon glyphicon-comment"></span>
       	Связаться с нами						
       <% end %> 
	    <%= link_to "", :class=>"btn btn-info btn-lg btn-block" do %>
			<span class="glyphicon glyphicon-save"></span>	
			Скачать брошюру		
       <% end %>      
 	</div> 
 </div>
</div>

app/views/courses/update_level_select.js.erb
$('#course_level_id').empty();

<% @levels.each do |level| %>
	 $("#course_level_id").append('<option value='+'<%= level.id %>'+'>'+'<%= level.name %>'+'</option>');
<% end %>