config/routes.rb
Academica4you::Application.routes.draw do

   root 'companies#index'
   
   resources :schools do
    collection do
      get :autocomplete
      get :get_addr_by_pos
     end
   end
   
   resources :companies, only: [:index, :new, :create, :edit, :update, :destroy]
   
   resources :courses, only: [:index, :new, :show, :create, :edit, :update, :destroy]
   
   resources :others, only: [:index]
   
   resources :languages, only: [:index, :new, :create, :edit, :update, :destroy]
   
   get 'courses/update_level_select/:id', :controller=>'courses', :action => 'update_level_select'
   
   resources :residences, only: [:index, :new, :create, :edit, :update, :destroy]
   
   resources :carts, only: [:index]
   
   resources :orders, only: [:new]

end

app/models/address.rb
class Address < ActiveRecord::Base
end

app/models/company.rb
class Company < ActiveRecord::Base
	has_many :schools
end

app/models/course.rb
class Course < ActiveRecord::Base
	has_many :course_durations
	has_many :lnk_school_courses
  	accepts_nested_attributes_for :course_durations, :reject_if => :all_blank, :allow_destroy => true
  	accepts_nested_attributes_for :lnk_school_courses, :reject_if => :all_blank, :allow_destroy => true
end

app/models/course_duration.rb
class CourseDuration < ActiveRecord::Base
	belongs_to :course
end

app/models/course_features.rb
class CourseFeatures < ActiveRecord::Base
end

app/models/currency.rb
class Currency < ActiveRecord::Base
end

app/models/exchange_rate.rb
class ExchangeRate < ActiveRecord::Base
end

app/models/geoplace.rb
class Geoplace < ApplicationRecord
	has_many :lnk_school_geoplaces
	belongs_to :geoplace_type
end

app/models/geoplace_type.rb
class GeoplaceType < ApplicationRecord
	has_many :geoplaces
end

app/models/lang_level.rb
class LangLevel < ActiveRecord::Base
	belongs_to :language
end

app/models/language.rb
class Language < ActiveRecord::Base
	has_many :lang_levels
  	accepts_nested_attributes_for :lang_levels, :reject_if => :all_blank, :allow_destroy => true
end

app/models/residence.rb
class Residence < ActiveRecord::Base
self.inheritance_column = nil
has_many :residence_durations
has_many :residence_features
  	accepts_nested_attributes_for :residence_durations, :reject_if => :all_blank, :allow_destroy => true
  	accepts_nested_attributes_for :residence_features, :reject_if => :all_blank, :allow_destroy => true
end

app/models/school.rb
class School < ActiveRecord::Base
   has_many :lnk_school_courses
   has_many :lnk_school_geoplaces
   accepts_nested_attributes_for :lnk_school_courses, :reject_if => :all_blank, :allow_destroy => true

   belongs_to :company
   
   searchkick text_middle: [:full_address_eng, :name], locations: [:location]
   #searchkick locations: [:location]

   #geocoded_by address: :full_address_eng

   # the callback to set longitude and latitude
   #after_validation :geocode

   def search_data
    attributes.merge(location: {lat: latitude, lon: longitude})
  end
end

app/controllers/residences_controller.rb
class ResidencesController < ApplicationController
	def index
		@residences = Residence.all
	end 
	
	def new
		@residence = Residence.new
		@schools = School.all.order(:name)
	end 
	
	def create
		@residence = Residence.new(residence_params)		
		if(@residence.save)
			logger.info "saving residence success"
		else
			logger.info "error when saving residence"
		end
		redirect_to residences_path
	end
	
	def edit
    	@residence = Residence.find(params[:id])
    	@schools = School.all.order(:name)
  	end
  	
  	def update
    @residence = Residence.find(params[:id])
      if @residence.update_attributes(residence_params)
        logger.info "updating residence success"
      else
        logger.info "error when updating residence"
      end
      redirect_to residences_path
  	end
  	
  	def destroy
    @residence = Residence.find(params[:id])
    @residence.destroy
    redirect_to residences_path
  end
	
	private 
 	def residence_params 
  		params.require(:residence).permit(:name, :description, :type, :school_id, 
  													residence_durations_attributes: 
  													[:id, :duration, :type, :price, :currency_id, :_destroy],
  													residence_features_attributes: 
  													[:id, :name, :description, :price, :currency_id, :_destroy]) 
 	end 
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/company_helper.rb
module CompanyHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/others_helper.rb
module OthersHelper
end

app/helpers/residences_helper.rb
module ResidencesHelper
end

app/helpers/school_helper.rb
module SchoolHelper
end

app/views/residences/_form.html.erb
	 <div class="title-box1 v2">
		<h3>Новое проживание</h3>
	 </div>  
  	<%= form_for(@residence, :html=>{:class=>"contact-form"}) do |f| %>
  		<div class="success-message">Contact form submitted!</div>	
			<%= f.label :name do %>
				<%= f.text_field :name, :type=>"text", :placeholder=>"Название" %>
			<% end %>
			<%= f.label :type do %>
				<%= f.text_field :type, :type=>"text", :placeholder=>"Тип" %>
			<% end %>
			<%= f.label :school_id do %>
  				<%= f.select :school_id, options_from_collection_for_select(@schools, "id", "name", @residence.school_id ) %>
			<% end %>	
			
			<%= f.label :description do %>
				<%= f.text_area :description, :placeholder=>"Описание" %>
			<% end %>
			
			<div class="form_btns title-box1 v2">
				<h3>Продолжительность проживания</h3>
	 		</div>  
			<%= f.label :residence_durations do %>
				<%= f.fields_for :residence_durations do |d| %>
	      		<%= render 'residence_duration_fields', :f => d %>
	      	<% end %>
	      <% end %>
	      
      	<div class="form_btns">
   			<%= link_to_add_association f, :residence_durations do %>
   				 Добавить продолжительность
   				 <i class="fa fa-plus"></i>
   			<% end %>
      	</div>
      	
      	<div class="form_btns title-box1 v2">
				<h3>Дополнительные опции проживания</h3>
	 		</div>  
			<%= f.label :residence_features do %>
				<%= f.fields_for :residence_features do |d| %>
	      		<%= render 'residence_feature_fields', :f => d %>
	      	<% end %>
	      <% end %>
	      
      	<div class="form_btns">
   			<%= link_to_add_association f, :residence_features do %>
   				 Добавить опции
   				 <i class="fa fa-plus"></i>
   			<% end %>
      	</div>
					
		   <div class="form_btns">
	     		<%= f.submit :'Сохранить', :class=>"more_btn" %>
			</div>
	<% end %>

app/views/residences/_residence_duration_fields.html.erb
<div class="nested-fields row marBot2">
	<div class="grid_3">
	<%= f.label :duration, :class=>"field" do %>
		<%= f.text_field :duration, :type=>"text", :placeholder=>"Продолжительность" %>
	<% end %>
	<%= f.label :type, :class=>"field" do %>
		<%= f.text_field :type, :type=>"text", :placeholder=>"Единица измерения" %>
	<% end %>
	<%= f.label :price, :class=>"field" do %>
		<%= f.text_field :price, :type=>"text", :placeholder=>"Стоимость" %>
	<% end %>
	</div>
	<div class="grid_3">
		<div class="form_btns marTop0">
		  <%= link_to_remove_association "Удалить", f %>
		</div>
	</div>
</div>

app/views/residences/_residence_feature_fields.html.erb
<div class="nested-fields row marBot2">
	<div class="grid_3">
	<%= f.label :name, :class=>"field" do %>
		<%= f.text_field :name, :type=>"text", :placeholder=>"Название" %>
	<% end %>
	<%= f.label :price, :class=>"field" do %>
		<%= f.text_field :price, :type=>"text", :placeholder=>"Стоимость" %>
	<% end %>
	<%= f.label :description, :class=>"field" do %>
		<%= f.text_area :description, :placeholder=>"Описание" %>
	<% end %>
	</div>
	<div class="grid_3">
		<div class="form_btns marTop0">
		  <%= link_to_remove_association "Удалить", f %>
		</div>
	</div>
</div>

app/views/residences/edit.js.erb
$('#new_residence_form').html("<%= j(render :partial=> 'form') %>");

app/views/residences/index.html.erb
<div class="menu_holder content_page">
	<div class="container">
		<div class="row">
			<div class="grid_12">
				<nav>
					<ul class="sf-menu header_menu sf-js-enabled">
						<li id="first-li"><%= link_to companies_path do %>Компании<strong></strong><% end %></a></li>
						<li><%= link_to schools_path do %>Школы<strong></strong><% end %></li>
						<li><%= link_to courses_path do %> Курсы<strong></strong><% end %></li>
						<li class="current"><%= link_to residences_path do %> Проживание<strong></strong><% end %></li>
						<li id="last-li"><%= link_to others_path do %> Прочее<strong></strong><% end %></li>
					</ul>
				</nav>
			</div>
		</div>
	</div>
</div>
<div class="container">
 	<div class="row">
		<div class="grid_2">
			<%= link_to "Добавить", new_residence_path, :class=>"more_btn", :remote=>true %>
		</div> 	
 	</div>
	<div id="new_residence_form" class="grid_8 hline3 marg-left-0"></div>
 	<div class="wrapper hline2">
			<div class="title-box1 v2">
				<h3>Проживание</h3>
			</div>
			<div class="title-box2">
				<span class="mar3">ID</span>
				<span class="mar3">Название ENG</span>
				<span>Описание</span>
			</div>		
			<ul class="listWithMarker">			
				<% @residences.each do |r| %>
					<li>
						<div class="grid_1">
							<span class="rank_num"><%= r.id %></span>					
						</div>
						<div class="grid_2"><%= r.name %></div>
						<div class="grid_6"><%= r.description %></div>
						<div class="grid_2">
							<%= link_to edit_residence_path(r), :remote=>true do %> 
								<i class="fa fa-edit"></i>
						 	<% end %>
						 	<%= link_to residence_path(r), :method => 'delete', data: { confirm: 'Удалить проживание "'+r.name+'"?' } do %> 
								<i class="fa fa-trash-o"></i>
						 	<% end %>		
						</div>
					</li>	
				<% end %>
			</ul>
 	</div>
</div>

app/views/residences/new.js.erb
$('#new_residence_form').html("<%= j(render :partial=> 'form') %>");